### ISSUE TITLE
Extension not yet compatible with TYPO3 7.6.15

### ISSUE THREAD

**Issue by basvanbeeknl** [haassie/rh_recaptcha#10]
tail -f /typo3temp/logs/typo3_c0e3c2e594.log

Mon, 20 Feb 2017 19:41:00 +0000 [ALERT] request="cab28531bc656" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 201702201940597f895b09 - {"exception":"exception 'TYPO3\\CMS\\Fluid\\View\\Exception\\InvalidTemplateResourceException' with message 'The partial files \"\", \"\", \"\/var\/www\/XXX.nl\/web\/typo3conf\/ext\/powermail\/Resources\/Private\/Partials\/Form\/Field\/Jhcaptcharecaptcha.html\", \"\/var\/www\/XXX.nl\/web\/typo3conf\/ext\/powermail\/Resources\/Private\/Partials\/Form\/Field\/Jhcaptcharecaptcha\" could not be loaded.' in \/shopcvs\/skeleton\/typo3_src-7.6.15\/typo3\/sysext\/fluid\/Classes\/View\/TemplateView.php:478

**Comment by haassie** [comment]
Based on the paths, I think this is a different extension ;-)
