### ISSUE TITLE
Wrong dependencies in TER

### ISSUE THREAD

**Issue by cyMarvin** [haassie/rh_recaptcha#11]
I'm using powermail 2.0.14 on a TYPO3 6.2.6 system and I receive an error message in the frontend after including static template and adding the field to my form.
The partials subfolder is set in TypoScript as "Form", in powermail 2.0.14 it is still called "Forms". In TER it says minimum 2.0.0 is required. Please update.

**Comment by haassie** [comment]
This is fixed in version 1.0
