### ISSUE TITLE
Undefined offset: 1 in MarkerBasedTemplateService.php on line 206 (Incompatible Extension)

### ISSUE THREAD

**Issue by Scunkaneli** [haassie/rh_recaptcha#12]
Hi,

when I checked for broken extentions in the Install Tool, the error message "Undefined offset: 1 in MarkerBasedTemplateService.php on line 206" was displayed together with the suggestion to remove rh_captcha. The extension is working fine (as long as I can tell), but there seems to be something wrong with it? 
I'm using Typo3 7.6.18, PHP 7.1.4 and powermail 3.18.0.

![screenshot](https://cloud.githubusercontent.com/assets/25462171/25637985/2749522a-2f87-11e7-9aab-1252468189de.png)

**Comment by haassie** [comment]
Thanks for reporting this issue. Will check it and fix it when needed.

**Comment by Scunkaneli** [comment]
Thank you.
I can confirm this is still present with latest powermail update 3.18.~~1~~ 2
Also I can confirm disabling the rh_recaptcha extension lets both error messages go away.
