### ISSUE TITLE
v1.1.1: Can't include template

### ISSUE THREAD

**Issue by Scunkaneli** [haassie/rh_recaptcha#16]
Using newest update of rh_recaptcha, I can't include the root template, which leads to this error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: The Fluid template files "/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/Recaptcha.html", "/typo3conf/ext/powermail/Resources/Private/Partials/Form/Field/Recaptcha" could not be loaded. | TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException thrown in file /typo3_src-8.7.1/vendor/typo3fluid/fluid/src/View/TemplatePaths.php in line 719`

I can include the root template (and use rh_recaptcha) by going back to version 1.0.0 (together with #13). 

System: CMS 8.7.1, PHP 7.1.4

**Comment by Sonezi** [comment]
I have a same issue. after update cant load recaptha template and on my form generate error (Oops an error occurred).. cant complete input on form. I am using recaptcha as another component of form from powermail extension as replacement for powermail captcha... :D

System: CMS 7.6.18, PHP 5.6.26 and Powermail 3.18.2

partial error log

Sun, 14 May 2017 23:18:51 +0200 [ALERT] request="f824e3b945909" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20170514231850474b2381 - {"exception":"exception 'TYPO3\\CMS\\Fluid\\View\\Exception\\InvalidTemplateResourceException' with message 'The partial files \"\/var\/www\/vhosts\/test.ch\/httpdocs\/typo3conf\/ext\/powermail\/Resources\/Private\/Partials\/Form\/Field\/Recaptcha.html\", \"\/var\/www\/vhosts\/test.ch\/httpdocs\/typo3conf\/ext\/powermail\/Resources\/Private\/Partials\/Form\/Field\/Recaptcha\" could not be loaded.'

**Comment by haassie** [comment]
What exactly do you try? Do you only include the static template of the rh_recaptcha plugin? Or do you have some additional typoscript?

**Comment by Scunkaneli** [comment]
Normally, to use the extension, I first have to include the rh_recaptcha Template into my webpages template. I basically mean this section: "include static template (from extensions)"

With the newest version of rh_recaptcha, there is no template displayed to be included. As I can't include its template, the formular with Recaptcha fails to load, as it is not able to find the rh_recaptcha template. 

When I revert back to v1.0.0, the template is again displayed in this "include static template view", I can include it and the forms load correctly. 

I hope I was able to discribe it a little better for you! To answer your question: No, I was not trying to include the template via typoscript - I'm just talking about including it via Backend.

**Comment by haassie** [comment]
I will have a look on it tomorrow morning.

Op ma 15 mei 2017 om 22:58 schreef Scunkaneli <notifications@github.com>

**Comment by Sonezi** [comment]
as for me, same as @Scunkaneli ... Same setup same problem... :)

**Comment by Scunkaneli** [comment]
I just created a fix. @Sonezi, can you confirm it works for you too?

**Comment by Sonezi** [comment]
@Scunkaneli sorry for delay answer. I can confirm now to have been enable to include recaptcha in static template, but now i have error that appeared to be closed issue...


Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property.

**Comment by baden32** [comment]
I tried to install rh_recaptcha	1.1.1 on Typo3 7.6.18 and I'm also unable to add reCaptcha template (reCaptcha is not listed). 
The above posts mentionned a fix. Is a fix already available on TER?
Regards,
Joel

**Comment by Scunkaneli** [comment]
Hey, the fix above is just a pull request from me which resolved the issue for me. Sadly, @Sonezi was not able to get the extension to work correctly (Seems to be a different issue). So no, the fix is not on TER, as @haassie has not reviewed my changes at the moment.

But you can just download [this file](https://github.com/Scunkaneli/rh_recaptcha/raw/master/Configuration/TCA/sys_template.php), named sys_template.php, and copy it to the following path:
`/rh_recaptcha/Configuration/TCA/sys_template.php` (Most likely, you have to create the TCA folder yourself)
That's literally the fix I proposed here on github. Could you please tell us if it worked for you?

@Sonezi: I've already tried to reproduce your issue, but sadly I was not able to do that - everything works fine here. Did you change something else on the plugin (eg. Template, special typoscript or tca,...)? Also, does your system log mention a specific location where this error is dropped (at which file (+line))?

**Comment by haassie** [comment]
I will check Tuesday.

We have it working correctly on a CMS 8.7.1 installation.

Op vr 19 mei 2017 om 21:09 schreef Scunkaneli <notifications@github.com>

**Comment by Scunkaneli** [comment]
Okay, thanks! Is it working on CMS 8.7.1 for you with the change I proposed or with another one / without any change on the code?

**Comment by haassie** [comment]
It works with the code of master.

Op vr 19 mei 2017 om 21:22 schreef Scunkaneli <notifications@github.com>

**Comment by Scunkaneli** [comment]
Hm that's weird. My cms seems to ignore the addStaticFile-code inside ext_localconf.php
What I changed was basically using addStaticFile inside sys_template TCA like described in [API documentation](https://typo3.org/api/typo3cms/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_extension_management_utility.html#a13ee6921557e1123c328a7dd3df9c576) instead of using it inside localconf.

**Comment by Sonezi** [comment]
any new updates for this problem?

**Comment by Scunkaneli** [comment]
If you are talking about being not able to include the template, then my fix is working fine for me. haassie already said he will have a look on it Tuesday.
If you are talking about your problem with mapping the property 'answers', then there is nothing I do know about it. If it will not be fixed by haassie Tuesday, then you could also open an exra issue for it, if you want.

In the meantime, you can of course use version 1.0.0, as this version does not include the problems

**Comment by Sonezi** [comment]
oke.. no problemo i don't have problems with enabling recaptcha an importing theme to static template, fix have worked this around well.. i try to bypass the given error with version 1.0.0... tnx meanwhile i hope you will find the fix for everything... :)

**Comment by Sonezi** [comment]
@Scunkaneli Hello I turn off option on powermail (Do you want confimation page) and captcha works, i mean it successfully finish form and complete redirect on home page..
i think that powermail in post request somehow loose information on captha even if it say its valid, but when sending futher it send empty property, maybe thats the error.. can you look into what can it be?

**Comment by Moongazer** [comment]
For me the current TER version 1.1.1 and also the current master-branch checkout doesn't work. In both versions I can*t select the template in the "include static template (from extensions)" list (it doens't show up there).

TYPO3 7.6.18
PHP 7.0
Windows 8.1

**Comment by baden32** [comment]
Did you try the "hack" posted by Scunkaneli  (see above)
link to replace /rh_recaptcha/Configuration/TCA/sys_template.php
Hope this helps

**Comment by Scunkaneli** [comment]
For now nobody reported my pull request not fixing their issue in over a month. I think it should be safe to include - It has been almost a month since @haassie said he'll look into it. Sadly I can't answer you when it will be fixed in master/on TER.
As @baden32 propsed, you should really try #17 and see if it will work for you.

@Sonezi For me both options, either with or without confirmation page, are working - Sadly I can't reproduce your issue.

**Comment by stroebjo** [comment]
I stumbled over this issue. The fix in #17 words for me! Thanks @Scunkaneli!

Typo3 7.6.18
PHP 7.0

**Comment by outdoorsman** [comment]
It looks like you've already closed this issue, but I'm experiencing this issue still with rh_recaptcha 1.1.1 in TYPO3 7.6.20. Not sure what else you need from me for more diagnotics. I'm just not able to include the info for rh_recaptcha in my TS template.

**Comment by Scunkaneli** [comment]
I have an idea why it isn't working:

Do you use the rh_recaptcha 1.1.1 from TER? Because this one was not updated since May 13, so it does not contain the fix. If this is your problem here, you should use the [master](https://github.com/haassie/rh_recaptcha/archive/master.zip) and it will work. The github version (also labeled v1.1.1) containing the fix has not been uploaded to the TER yet.

**Comment by outdoorsman** [comment]
Hello @Scunkaneli, great thoughts. I am using composer and it's pointed to `typo3-ter/rh-recaptcha`. So would that mean that I'm using an up to date version or not... I was having a hard time understanding exactly what was where??

**Comment by Scunkaneli** [comment]
Hi @Outdoorsman, sorry for the very late reply. If you still weren't able to figure it out or switched to another solution, here's the thing you have to do:
Download current master from [here](https://github.com/haassie/rh_recaptcha/archive/master.zip) (newest version of the ext, newer than on TER). Then you have to upload it to your Typo3 CMS (either via FTP or in the Backend). Then the extension should work.

The fix still was not pushed to the TER so the version on the TER is outdated and does not contain the fix
