### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by haassie** [haassie/rh_recaptcha#2]
Provide a manual for the extension

**Comment by SventB** [comment]
Please describe there how to overwrite the error message ("Captcha: Possible robot detected! ")

**Comment by SventB** [comment]
It seems this is the only possibility:

``` php
$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['EXT:rh_recaptcha/Resources/Private/Language/locallang.xlf'][] = 'EXT:my_ext/Resources/Private/Language/Plugin/RhRecaptcha/locallang.xlf';
$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['EXT:rh_recaptcha/Resources/Private/Language/de.locallang.xlf'][] = 'EXT:my_ext/Resources/Private/Language/Plugin/RhRecaptcha/de.locallang.xlf';
```

**Comment by haassie** [comment]
In that case it is a bug. Please report a new issue for this and I will try to fix that this week.

**Comment by SventB** [comment]
I created a new ticket: #5

**Comment by haassie** [comment]
Thank you. The manual (without translation) is now added to the repository and can be viewed on https://docs.typo3.org/typo3cms/extensions/rh_recaptcha/
