### ISSUE TITLE
Translation of text

### ISSUE THREAD

**Issue by SventB** [haassie/rh_recaptcha#5]
The text "Possible robot detected" seems not to be modifiable with TypoScript.
I tried:

```
plugin.rh_recaptcha._LOCAL_LANG.de.validation.possible_robot = My new text
plugin.tx_rhrecaptcha < plugin.rh_recaptcha
plugin.tx_powermail < plugin.rh_recaptcha
```

and more.

It seems to be only possible with this (localconf.php):

``` php
$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['EXT:rh_recaptcha/Resources/Private/Language/locallang.xlf'][] = 'EXT:my_ext/Resources/Private/Language/Plugin/RhRecaptcha/locallang.xlf';
$TYPO3_CONF_VARS['SYS']['locallangXMLOverride']['EXT:rh_recaptcha/Resources/Private/Language/de.locallang.xlf'][] = 'EXT:my_ext/Resources/Private/Language/Plugin/RhRecaptcha/de.locallang.xlf';
```

**Comment by haassie** [comment]
Added updated manual in 1bd00044fa64052d946fce027f0311a94458df9b.

You can use your own translations by the following TypoScript:

```
plugin.tx_rh_recaptcha._LOCAL_LANG.de.validation.possible_robot = My new text
```

**Comment by SventB** [comment]
Thank you!
The key "tx_rh_recaptcha" (with underscore) is pretty unusual. Do you know why it is not "tx_rhrecaptcha"?

**Comment by haassie** [comment]
You are completely right. I fixed that now so it should work with tx_rhrecaptcha instead of tx_rh_recaptcha. Please use version 0.1.1 of the extension. Will be in TER any moment.
