### ISSUE TITLE
no siteKey

### ISSUE THREAD

**Issue by afineske** [haassie/rh_recaptcha#6]
Hi,

i have install the extension as in the documentation. But i have this message:

No siteKey provided in TypoScript constants
See here: http://fineske.com/index.php?id=18

Thanks for help

Andreas

**Comment by haassie** [comment]
Hi Andreas,

Did you follow the steps in https://docs.typo3.org/typo3cms/extensions/rh_recaptcha/Installation/Index.html#configure-extension? https://docs.typo3.org/typo3cms/extensions/rh_recaptcha/Installation/Index.html#configure-extension?

Regards,

Richard

**Comment by afineske** [comment]
Yes i have put the code in the constansts, the TSConfig and in typoscript nothing works.

Please help

**Comment by haassie** [comment]
Do you see the value of the siteKey if you are evaluating plugin.tx_powermail.settings.setup.reCAPTCHA.siteKey within the TypoScript Object Browser in backend?

**Comment by afineske** [comment]
Yes
![tsobj](https://cloud.githubusercontent.com/assets/11649139/10603859/e0108308-7720-11e5-944b-4e318d1cea8a.png)

**Comment by haassie** [comment]
This is within Constants I think? And what about the setup part? Because i’m missing the setup part within this path if this is the setup already.

**Comment by afineske** [comment]
what must in the setup part?

**Comment by haassie** [comment]
That is done by the static include. i assume you added the static template
of the rh_recaptcha?

Op dinsdag 20 oktober 2015 heeft zippo-71 notifications@github.com het
volgende geschreven:

**Comment by afineske** [comment]
Yes Look:
![bildschirmfoto 2015-10-20 um 15 32 40](https://cloud.githubusercontent.com/assets/11649139/10608568/e47a6a52-773f-11e5-8373-a9069e62ea9c.png)

**Comment by haassie** [comment]
Then you should have plugin.tx_powermail.settings.setup.reCAPTCHA.siteKey in your setup part.

**Comment by afineske** [comment]
![bildschirmfoto 2015-10-20 um 15 36 18](https://cloud.githubusercontent.com/assets/11649139/10608715/8372a0ac-7740-11e5-9d6f-8d7b308c0a7a.png)
What is wrong?

**Comment by haassie** [comment]
In your TypoScript Object Browser: Do you see (in setup) the value of your siteKey at the path of my previous message? I think it has something to do with the order of loading your TypoScript templates because for now I can’t reproduce this error.

**Comment by afineske** [comment]
yes see here:
![bildschirmfoto 2015-10-20 um 15 52 37](https://cloud.githubusercontent.com/assets/11649139/10609190/bff09e9c-7742-11e5-8ce8-11a985854098.png)

**Comment by haassie** [comment]
Strange. Also that i see the siteKey is set twice. with and without the setup part. If you want, you can give me an admin-account to the website and I wil check what is wrong. If so, please send a temporary user account to my personal e-mailaddress.

**Comment by afineske** [comment]
I have send the email

**Comment by haassie** [comment]
It is working now. You did an include of the static on the root page as well as on the contactpage. This caused an empty value for plugin.tx_powermail.settings.setup.reCAPTCHA.siteKey on the contact page. I simply removed the static include of reCAPTCHA on the contact page and it is working now.

**Comment by afineske** [comment]
OK Thanks
